package adp_db;

import java.util.ArrayList;

import adp_tiers.Tier;

public class ADPElementTier extends ArrayList<ADPElement> {
	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 6208165650247477580L;

	public final int tierIndex;
	public final int pos;
	public final int low, high;

	public ADPElementTier(final int pos, final Tier tier, final ADPDatabase db) {
		super();
		this.pos = pos;
		this.tierIndex = tier.tierIndex;
		this.low = tier.low;
		this.high = tier.high;

		for (final ADPElement player : db) {
			if (player.rank >= tier.low && player.rank <= tier.high)
				this.add(player);
		}
	}

	public ADPElementTier(int pos, int i, ADPElement player) {
		super();
		this.pos = pos;
		this.tierIndex = i;
		this.add(player);
		this.low = this.high = player.rank;
	}
}
