package adp_db;

import java.util.ArrayList;

public class ADPPOSTiers extends ArrayList<ADPElementTier> {
	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 1612788752039792752L;

	public final int pos;

	public ADPPOSTiers(final int pos) {
		super();
		this.pos = pos;
	}

	public void placePlayer(ADPElement player) {
		final int rank = player.rank;

		if (this.size() < 2) {
			if (this.isEmpty())
				this.add(new ADPElementTier(player.pos, 1, player));
			else {
				// just add player to this only tier
				this.get(0).add(player);
			}
			return;
		}

		int index = 0;
		ADPElementTier bottom = this.get(index++);
		ADPElementTier top = this.get(index++);

		while (rank <= bottom.high || rank >= top.low) {
			bottom = top;
			if (index < this.size()) {
				top = this.get(index++);
			} else {
				bottom.add(player);
				return;
			}
		}

		if (rank - bottom.high < top.low - rank)
			bottom.add(player);
		else
			top.add(player);
	}
}
