package adp_db.gui;

import javax.swing.BoxLayout;
import javax.swing.JComponent;
import javax.swing.JLabel;

import adp_db.ADPElement;
import drafter.Draft;

public class TeamRoundDisplay extends JComponent {

	/**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = -3888014840901394113L;

	public static final double THRESHOLD = 0.01;
	public static final double MAX_RESULTS = 20;

	public final int teamIndex;
	private final Draft draft;
	private int round;
	private final TierColoring tierColoring;

	public TeamRoundDisplay(final Draft draft, final int teamIndex,
			final int round, final TierColoring tierColoring) {
		this.tierColoring = tierColoring;
		this.teamIndex = teamIndex;
		this.draft = draft;

		this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

		setRound(round);
	}

	public void setRound(final int round) {
		this.round = round;
		updatePanel();
		this.validate();
	}

	public void updatePanel() {
		this.removeAll();
		final int pick = draft.getTeamNthSelection(teamIndex, round);
		this.add(new JLabel("Round " + round + ", Pick " + pick));

		draft.sortDB(pick - draft.currentPick() + 1);

		int count = 0;
		for (final ADPElement player : draft) {
			if (player.getP() > THRESHOLD && count++ < MAX_RESULTS) {
				final JLabel label = new JLabel("p: " + round2(player.getP())
						+ ": " + player.name + ", ADP: "
						+ round1(player.getAVGRank()) + ", RNK: "
						+ player.getRank());

				label.setOpaque(true);
				label.setBackground(tierColoring.getColor(player));

				this.add(label);
			}
		}
	}

	public static String round2(final double val) {
		final int hun = (int) (val * 100.0);
		final int num = hun / 100;
		final int dec = (hun - 100 * num);
		return num + "." + (dec < 10 ? "0" : "") + dec;
	}

	public static String round1(final double val) {
		final int hun = (int) (val * 10.0);
		final int num = hun / 10;
		final int dec = hun - 10 * num;

		String ans = num + "." + dec;

		// System.err.println("hun: " + hun + ", num: " + num);
		// System.err.println(ans);

		return ans;
	}
}
